import Head from "next/head";
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Whatsapp by Deni</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Sidebar />
    </div>
  );
}
